online_shop/cart/urls.py
# coding: utf-8
# Konstantyn Davidenko

from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^delete/(?P<product_id>\d+)/$', views.CartDelete, name='CartDelete'),
    url(r'add/(?P<product_id>\d+)/$', views.CartAdd,name="CartAdd"),
]

online_shop/online_shop/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from online_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'payment/', include(('payment.urls', 'payment'), namespace='payment')),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'contacts/', include(('contacts.urls', 'contacts'), namespace='contacts')),
    url(r'^', include(('shop.urls', 'shop'), namespace='shop'))


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/shop/urls.py
# coding: utf-8
# Konstantyn Davidenko

from django.conf.urls import url
from django.urls import re_path

from . import views

urlpatterns = [
    # url('list/$', views.ProductList, name='ProductList'),
    url('list/$', views.AllProduct.as_view(), name='ProductList'),
    url('(?P<id>\d+)$', views.ProductDetail, name='ProductDetail'),
    re_path(r'list/?', views.Search.as_view(), name='search'),
    url('^$', views.MainPage, name='home'),
]

online_shop/shop/models.py
from django.db import models
from django.conf import settings

# Модель продукта
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе")

    class Meta:
        ordering = ['name']
        index_together = [
            ['id']
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[self.id])

    # def save(self, **kwargs):
    #     print(kwargs.items())
    #     im = Image.open(self.image)
    #     output = BytesIO()
    #     im = im.resize((100, 100))
    #     im.save(output, format='JPEG', quality=100)
    #     output.seek(0)
    #     self.img = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.img.name.split('.')[0], 'image/jpeg',
    #                                     sys.getsizeof(output), None)
    #     super(Product, self).save(kwargs)


class ProductImages(models.Model):
    property = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=settings.MEDIA_DIR + 'product/%Y/%m/%d/', blank=True, verbose_name="Изображение товара")

online_shop/shop/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, render_to_response

from cart.cart import Cart
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.list import MultipleObjectMixin, ListView

from .models import Product


# Страница с товарами
def MainPage(request):
    cart = Cart(request)
    return render(request, 'shop/index.html', {'cartItems': cart})


def ProductList(request):
    products = Product.objects.all()
    cart = Cart(request)
    return render(request, 'shop/product/list.html', {
        'products': products, 'cartItems': cart})


# Страница товара
def ProductDetail(request, id):
    product = get_object_or_404(Product, id=id)
    # cart_product_form = CartAddProductForm()
    # return render(request, 'shop/product/detail.html',{'product': product,'cart_product_form': cart_product_form})
    return render(request, 'shop/product/detail.html', {'product': product})


class AllProduct(TemplateView):
    template_name = 'shop/product/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()
        paginator = Paginator(products, 6)  # Show 25 contacts per page
        page = self.request.GET.get('page')
        page_products = paginator.get_page(page)
        context['products'] = page_products
        return context


class Search(TemplateView):
    template_name = 'shop/product/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get('name')
        products = Product.objects.filter(name__contains=name)
        paginator = Paginator(products, 6)  # Show 25 contacts per page
        page = self.request.GET.get('page')
        page_products = paginator.get_page(page)
        context['products'] = page_products
        context['queries'] = products
        return context


from django import template
register = template.Library()


@register.simple_tag(takes_context=True)
def url_replace(context, **kwargs):
    query = context['request'].GET.copy()
    query.update(kwargs)
    return query.urlencode()

online_shop/shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% block content %}
<style>

</style>
<div id="itemDetail" class="main content">
    <div class="detailDescription">
        <div class="big_view">
            <img class="" src="{{product.images.first.image.url}}" width="311" height="319"/><br/>

        </div>
        <div class="scroll">
            {% for image in product.images.all %}
            <a href="#">
                <img onclick="onClick(this)" class="modal-hover-opacity " src="{{ image.image.url }}" width="62"
                     height="62"/>
            </a>
            {% endfor %}
        </div>
    </div>

    <div class="detailDescription">
        <h4>{{product.name}}</h4><br/>
        <span>{{product.price}} грн</span>
        <div class="">
            <p>
                <strong>Описание</strong>
                <br/>
                {{ product.description }}
            </p>
            <p>
                <a href="{% url 'cart:CartAdd' product_id=product.id %}" class="buy">Купить</a>
            </p>

        </div>
    </div>
</div>


<div id="modal01" class="modal" onclick="this.style.display='none'">
    <a href="#"><span class="close">&times;&nbsp;&nbsp;&nbsp;&nbsp;</span></a>
    <div class="modal-content">
        <img id="img01" style="max-width:100%">
    </div>
</div>

<script>
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
}




</script>
{% endblock %}

online_shop/shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% block content %}
{% load my_tags %}

<div id="main" class="main content">

    <form method="get" action="{% url 'shop:search'%}">
        <input type="search" name="name">
        <input type="submit" value="поиск">
    </form>

    <div class="items row">
        {% for product in products %}

        <div class="item">
            <a href="{% url 'shop:ProductDetail' product.id %}">
                <!--<img src="{{product.image.url}}" alt="" width="202" height="173"/>-->
                <img src="{{product.images.first.image.url}}" alt="" width="202" height="173"/>
                <br/>
            </a>
            <div class="price">
                {{product.name}}
            </div>
            <div class="price">
                {{product.price}}грн.
            </div>
        </div>
        {% endfor %}
    </div>
</div>
    <div class="pagination">
        <span class="step-links">
            {% if products.has_previous %}
                <a href="?{% url_replace request 'page' 1 %}">&laquo; first</a>
                <a href="?{% url_replace request 'page' products.previous_page_number %}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ products.number }} of {{ products.paginator.num_pages }}.
            </span>
            {% if products.has_next %}
                <a href="?{% url_replace request 'page' products.next_page_number %}">next</a>
                <a href="?{% url_replace request 'page' products.paginator.num_pages %}">last &raquo;</a>
            {% endif %}
        </span>
    </div>



{% endblock %}