online_shop/cart/urls.py
# coding: utf-8
# Konstantyn Davidenko

from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^delete/(?P<product_id>\d+)/$', views.CartDelete, name='CartDelete'),
    url(r'add/(?P<product_id>\d+)/$', views.CartAdd,name="CartAdd"),
]

online_shop/contacts/urls.py
# coding: utf-8
# Konstantyn Davidenko


from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^contacts$', views.ContactsView, name='contacts'),
    url(r'^pay_ship$', views.PayShipment, name='pay_ship'),
]

online_shop/online_shop/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from online_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'payment/', include(('payment.urls', 'payment'), namespace='payment')),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'contacts/', include(('contacts.urls', 'contacts'), namespace='contacts')),
    url(r'^', include(('shop.urls', 'shop'), namespace='shop'))


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/shop/urls.py
# coding: utf-8
# Konstantyn Davidenko

from django.conf.urls import url
from django.urls import re_path

from . import views

urlpatterns = [
    # url('list/$', views.ProductList, name='ProductList'),
    url('list/$', views.AllProduct.as_view(), name='ProductList'),
    url('(?P<id>\d+)$', views.ProductDetail, name='ProductDetail'),
    re_path(r'list/?', views.Search.as_view(), name='search'),
    url('^$', views.MainPage, name='home'),
]

online_shop/cart/models.py
from django.db import models

# Create your models here.

online_shop/shop/models.py
from django.db import models
from django.conf import settings

# Модель продукта
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе")

    class Meta:
        ordering = ['name']
        index_together = [
            ['id']
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[self.id])

    # def save(self, **kwargs):
    #     print(kwargs.items())
    #     im = Image.open(self.image)
    #     output = BytesIO()
    #     im = im.resize((100, 100))
    #     im.save(output, format='JPEG', quality=100)
    #     output.seek(0)
    #     self.img = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.img.name.split('.')[0], 'image/jpeg',
    #                                     sys.getsizeof(output), None)
    #     super(Product, self).save(kwargs)


class ProductImages(models.Model):
    property = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=settings.MEDIA_DIR + 'product/%Y/%m/%d/', blank=True, verbose_name="Изображение товара")

online_shop/cart/forms.py
# coding: utf-8
# Konstantyn Davidenko

from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество")


update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

online_shop/cart/views.py
# Create your views here.

from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .cart import Cart


def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product)
    return redirect('cart:CartDetail')


def CartDelete(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.delete(product)
    return redirect('cart:CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

online_shop/shop/views.py
from django.core.paginator import Paginator
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404, render_to_response

from cart.cart import Cart
from django.views import View
from django.views.generic import TemplateView
from django.views.generic.list import MultipleObjectMixin, ListView

from .models import Product


# Страница с товарами
def MainPage(request):
    cart = Cart(request)
    return render(request, 'shop/index.html', {'cartItems': cart})


def ProductList(request):
    products = Product.objects.all()
    cart = Cart(request)
    return render(request, 'shop/product/list.html', {
        'products': products, 'cartItems': cart})


# Страница товара
def ProductDetail(request, id):
    product = get_object_or_404(Product, id=id)
    # cart_product_form = CartAddProductForm()
    # return render(request, 'shop/product/detail.html',{'product': product,'cart_product_form': cart_product_form})
    return render(request, 'shop/product/detail.html', {'product': product})


class AllProduct(TemplateView):
    template_name = 'shop/product/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()
        paginator = Paginator(products, 6)  # Show 25 contacts per page
        page = self.request.GET.get('page')
        page_products = paginator.get_page(page)
        context['products'] = page_products
        return context


class Search(TemplateView):
    template_name = 'shop/product/list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get('name')
        products = Product.objects.filter(name__contains=name)
        paginator = Paginator(products, 6)  # Show 25 contacts per page
        page = self.request.GET.get('page')
        page_products = paginator.get_page(page)
        context['products'] = page_products
        context['queries'] = products
        return context


from django import template
register = template.Library()


@register.simple_tag(takes_context=True)
def url_replace(context, **kwargs):
    query = context['request'].GET.copy()
    query.update(kwargs)
    return query.urlencode()

online_shop/shop/templates/shop/base.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" type="text/css" href="{% static "style.css" %}"/>
        <link rel="stylesheet" type="text/css" href="{% static "style2.css" %}"/>
        <link rel="stylesheet" type="text/css" href="{% static "cart_style.css" %}"/>
        <link rel="stylesheet" type="text/css" href="{% static "style_order.css" %}"/>

        {% block title %}
            <title>piTon</title>
        {% endblock %}
    </head>
<body>

  <section id="header">
      {% include "shop/header.html"%}
  </section>


      {% block content %}{% endblock %}


    <section id="footer">
        {% include "shop/footer.html"%}
    </section>
</body>

</html>

online_shop/shop/templates/shop/cart.html
{% block cart %}
<div class="modal" id="cartModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Корзина</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container mb-4">
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th scope="col">Изображение</th>
                                        <th scope="col">Продукт</th>
                                        <th scope="col">Доступность</th>
                                        <th scope="col" class="text-center">Количество</th>
                                        <th scope="col" class="text-right">Цена</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for cartItem in cartItems %}
                                        {% with product=cartItem.product %}
                                            <tr>
                                                <td>
                                                    <a href="{{ product.get_absolute_url }}">
                                                        <img src="{{ product.image.url }}" class="img-responsive" />
                                                    </a>
                                                </td>
                                                <td>{{ product.name }}</td>
                                                <td>In stock</td>
                                                <td><input class="form-control" type="text" value="1"/></td>
                                                <td class="text-right num">{{ item.price }}</td>
                                                <td class="text-right">
                                                    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                                </td>
                                            </tr>
                                        {% endwith %}
                                    {% endfor %}
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td>Sub-Total</td>
                                        <td class="text-right">255,90 €</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td>Shipping</td>
                                        <td class="text-right">6,90 €</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td><strong>Total</strong></td>
                                        <td class="text-right"><strong>346,90 €</strong></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="col mb-2">
                            <div class="row">
                                <div class="col-sm-12  col-md-6">
                                    <button class="btn btn-block btn-light">Продолжить покупки</button>
                                </div>
                                <div class="col-sm-12 col-md-6 text-right">
                                    <button class="btn btn-lg btn-block btn-success text-uppercase">Оформить</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Сохранить</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

online_shop/shop/templates/shop/footer.html
{% block footer %}
<!-- Footer -->
{% load staticfiles %}
<div class="footer">
	<div class="colfirst">
		<p>Будем на связи</p>
		<a href="https://www.instagram.com/piton_ns/?hl=ru"><img src="{% static "instagram.png" %}" alt="instagram"></a>
	</div>
	<div class="colsecond">
		<p>Давай дружить</p>
	</div>
	<div class="colthird">
		<p>Нужна помощь?</p>
		<p>+38 095 514 51 98</p>
		<p>email.piton@gmail.com</p>
	</div>
</div>

{% endblock %}

online_shop/shop/templates/shop/header.html
{% load staticfiles %}
<div class="header">
	<div class="logo">
		<a href="{% url 'shop:home' %}">
			<img src="{% static "logo.png" %}" alt="logo">
		</a>
	</div>

	<div class="row">
		<div class="col-1">
			<a href="{% url 'shop:home' %}"> Главная </a>
		</div>
		<div class="col-1">
			<a href="{% url 'shop:ProductList' %}"> Магазин </a>
		</div>
		<div class="col-1">
			<a href="{% url 'contacts:pay_ship' %}"> Оплата и доставка </a>
		</div>
		<div class="col-1">
			<a href="{% url 'contacts:contacts' %}"> Контакты </a>
		</div>
		<div class="col-1">
			<a href="{% url 'cart:CartDetail' %}"> Корзина </a>
		</div>
	</div>
</div>

online_shop/shop/templates/shop/index.html
{% extends 'shop/base.html' %}
{% block content %}
{% load staticfiles %}
<div class="main">
	<div class="mainPicture">
		<img src="{% static "background.jpeg" %}" alt="background">
	</div>
	<div class="mainText">
		<p> <i>Мода - вопрос денег <p>Стиль - вопрос индивидуальности</p></i></p>
	</div>
</div>
{% endblock %}