online_shop/cart/urls.py
# coding: utf-8
# Konstantyn Davidenko

from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^delete/(?P<product_id>\d+)/$', views.CartDelete, name='CartDelete'),
    url(r'add/(?P<product_id>\d+)/$', views.CartAdd,name="CartAdd"),
]

online_shop/online_shop/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from online_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'payment/', include(('payment.urls', 'payment'), namespace='payment')),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'contacts/', include(('contacts.urls', 'contacts'), namespace='contacts')),
    url(r'^', include(('shop.urls', 'shop'), namespace='shop'))


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_shop/orders/urls.py
# coding: utf-8
# Konstantyn Davidenko


from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate'),
]

online_shop/shop/urls.py
# coding: utf-8
# Konstantyn Davidenko

from django.conf.urls import url
from django.urls import re_path

from . import views

urlpatterns = [
    # url('list/$', views.ProductList, name='ProductList'),
    url('list/$', views.AllProduct.as_view(), name='ProductList'),
    url('(?P<id>\d+)$', views.ProductDetail, name='ProductDetail'),
    re_path(r'list/?', views.Search.as_view(), name='search'),
    url('^$', views.MainPage, name='home'),
]

online_shop/cart/models.py
from django.db import models

# Create your models here.

online_shop/cart/forms.py
# coding: utf-8
# Konstantyn Davidenko

from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество")


update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

online_shop/cart/views.py
# Create your views here.

from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .cart import Cart


def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product)
    return redirect('cart:CartDetail')


def CartDelete(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.delete(product)
    return redirect('cart:CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

online_shop/cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load staticfiles %}
{% block content %}

<div class="main container content">
    <div class="cart transition is-open">
        <div class="table">
            <div class="layout-inline row th">
                <div class="col col-pro">Товар</div>
                <div class="col col-price align-center">Цена</div>
                <div class="col col-qty align-center">Количество</div>
                <div class="col">стоимость</div>
            </div>
            {% for item in cart %}
            <div class="layout-inline row cartItem">
                <div class="col col-pro layout-inline">
                    <a href="{% url 'shop:ProductDetail' item.product.id %}">
                        <img class="cartImg" src="{{ item.product.images.first.image.url }}" alt="kitten"/>
                    </a>
                    <h2>{{ item.product.name}}</h2>
                </div>

                <div class="col col-price col-numeric align-center ">
                    <p>{{item.product.price}}</p>
                </div>

                <div class="col col-qty layout-inline">
                    <a href="{% url 'cart:CartRemove' product_id=item.product.id %}" class="qty qty-minus">-</a>
                    <input type="numeric" value="{{ item.quantity}}"/>
                    <a href="{% url 'cart:CartAdd' product_id=item.product.id %}" class="qty qty-plus">+</a>
                </div>

                <div class="col col-total col-numeric"><p>{{item.total_price}}</p>
                </div>
            </div>
            {% endfor %}
        </div>

        <a href="{% url 'orders:OrderCreate' %}">
            <button>Заказать</button>
        </a>

    </div>
</div>

<div id="modalPay" class="modal" onclick="this.style.display='none'">
    <a href="#"><span class="close">&times;&nbsp;&nbsp;&nbsp;&nbsp;</span></a>
    <div class="modal-content">
        <div id="liqpay_checkout"></div>
    </div>
</div>

<script src="//static.liqpay.ua/libjs/checkout.js" async></script>
<script>
    window.LiqPayCheckoutCallback = function() {
    LiqPayCheckout.init({
        data: "{{ data }}",
        signature: "{{ signature }}",
        embedTo: "#liqpay_checkout",
        mode: "embed" // embed || popup,
    }).on("liqpay.callback", function(data){
        console.log(data.status);
        console.log(data);
    }).on("liqpay.ready", function(data){
        // ready
    }).on("liqpay.close", function(data){
        // close
    });

    function payOrder() {
        document.getElementById("modalPay").style.display = "block";
    }


</script>

{% endblock %}